### PR TITLE
refactor molden reader

### PR DESCRIPTION
**Pull request by chstem**
I refactored the molden reader to make it more linear and not loop over the molden file twice. This hopefully makes the code easier to read and maintain.

If mixed or ambigious flags for cartesian/spherical basis functions are available, it first removes any flags for unused angular momentum and then checks whether spherical flags remain or not. If necessary this behavior may be changed by modifiying
https://github.com/orbkit/orbkit/blob/0acb61db7a7aa35929cf75653e123a2cc182383d/orbkit/read/molden.py#L232

`orbkit test` runs through without issues. If no other problems show up, this can be merged.

### CODE REVIEW

**Comment by vpohl** [comment]
I just had a quick look into your code. There seems to be one problem. How can you be sure that the molden file ends after the [MO] block? For instance, a molden file may contain vibrational information or even energy convergence information.

**Comment by chstem** [comment]
I guess in this case it will just ignore the additional information. But the old reader did the same thing, right? So at least this would not break anything. If required, one needs to implemented it anyway.

But there is another issue: the new code assumes the [MO] block comes after the [atoms ] and [GTO] block. So far, all molden files I have seen follow this order. So this might not really be an issue.

**Comment by vpohl** [comment]
@chstem Should this branch be merged?

**Comment by chstem** [comment]
Yes, please.

**Pull request merged**
